<Project Sdk="Microsoft.NET.Sdk.Razor">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <AddRazorSupportForMvc>true</AddRazorSupportForMvc>
  </PropertyGroup>

  <ItemGroup>
    <FrameworkReference Include="Microsoft.AspNetCore.App" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="theSTRIDEsPath.theCalendar" Version="0.26.270.1152" />
    <PackageReference Include="theSTRIDEsPath.theCharts" Version="0.26.255.1335" />
    <PackageReference Include="theSTRIDEsPath.theInteractDragDrop" Version="0.26.263.1544" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\theDatabase\theDatabase.csproj" />
    <ProjectReference Include="..\theInfrastructure\theInfrastructure.csproj" />
  </ItemGroup>



</Project>
